name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - "weatherkit.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            index.html
            weatherkit.yaml
            README.md

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
